require:
  - rubocop-rails
  - rubocop-rspec

Style/Documentation:
  Enabled: false

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/HashSyntax:
  EnforcedShorthandSyntax: never

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**'
    - 'db/**'
