version: '3.8'
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    command: redis-server
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - redis:/data

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3000:3000"
    depends_on:
      - xpg

  xpg:
    image: snex00/xpg:latest
    volumes:
      - assets:/app/public/assets
      - qr_codes:/app/storage
      - wallets:/app/wallets
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ["foreman", "start"]
    env_file:
      - '.env.docker'

volumes:
  assets:
  redis:
  postgres:
  qr_codes:
  wallets:
