version: '3.8'
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - '.env.docker'

  redis:
    image: redis:alpine
    command: redis-server
    volumes:
      - redis:/data
    env_file:
      - '.env.docker'

  web:
    build: .
    volumes:
      - .:/opt
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
      - '.env.docker'

volumes:
  redis:
  postgres:
