version: '3.8'
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    command: redis-server
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - redis:/data

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      xpg:
        condition: service_healthy
    ports:
      - "3000:3000"

  sidekiq:
    image: snex00/xpg:latest
    volumes:
      - wallets:/app/wallets
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      xpg:
        condition: service_healthy
    command: ["bundle", "exec", "sidekiq", "-q", "default"]

    # Since the monero RPC needs to be accessible on localhost, sidekiq scaling should only be done through
    # the sidekiq concurrency option. You can only have ONE sidekiq container.
    scale: 1
    entrypoint: ''
    env_file:
      - '.env.docker'

  xpg:
    image: snex00/xpg:latest
    volumes:
      - qr_codes:/app/storage
    healthcheck:
      test: ["CMD", "curl", "-I", "HEAD", "http://localhost:3000"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ["bundle", "exec", "puma", "-C", "config/puma.rb", "-p", "3000"]

    # Feel free to scale this up to your heart's desire.
    scale: 1
    env_file:
      - '.env.docker'

volumes:
  redis:
  postgres:
  qr_codes:
  wallets:
