default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: xpg_development

test:
  <<: *default
  database: xpg_test

staging:
  <<: *default
  database: xpg_staging

production:
  <<: *default
  database: xpg
