development:
  create_wallet: 'log-file=/dev/null&rpc-login=%rpc_creds%&rpc-bind-port=%port%&wallet-dir=wallets/development&stagenet=true&daemon-host=%daemon%'
  rpc_wallet:    'log-file=/dev/null&rpc-login=%rpc_creds%&rpc-bind-port=%port%&wallet-file=wallets/development/%name%&password=%password%&stagenet=true&daemon-host=%daemon%&tx-notify=%tx_notify% %id% %s'

test:
  create_wallet: 'log-file=/dev/null&rpc-login=%rpc_creds%&rpc-bind-port=%port%&wallet-dir=wallets/test&stagenet=true&daemon-host=%daemon%'
  rpc_wallet:    'log-file=/dev/null&rpc-login=%rpc_creds%&rpc-bind-port=%port%&wallet-file=wallets/test/%name%&password=%password%&stagenet=true&daemon-host=%daemon%&tx-notify=%tx_notify% %id% %s'

staging:
  create_wallet: 'log-file=/dev/null&rpc-login=%rpc_creds%&rpc-bind-port=%port%&wallet-dir=wallets/staging&stagenet=true&daemon-host=%daemon%'
  rpc_wallet:    'log-file=/dev/null&rpc-login=%rpc_creds%&rpc-bind-port=%port%&wallet-file=wallets/staging/%name%&password=%password%&stagenet=true&daemon-host=%daemon%&tx-notify=%tx_notify% %id% %s'

production:
  create_wallet: 'log-file=/dev/null&rpc-login=%rpc_creds%&rpc-bind-port=%port%&wallet-dir=wallets/production&daemon-host=%daemon%'
  rpc_wallet:    'log-file=/dev/null&rpc-login=%rpc_creds%&rpc-bind-port=%port%&wallet-file=wallets/production/%name%&password=%password%&daemon-host=%daemon%&tx-notify=%tx_notify% %id% %s'
