:scheduler:
  :schedule:
    spawn_monero_rpc_wallets_job:
      every: ['1m', first_in: '0s']
      class: SpawnMoneroRpcWalletsJob
    refresh_avg_block_time_cache_job:
      every: ['1h', first_in: '0']
      class: RefreshAvgBlockTimeCacheJob
    save_wallets:
      every: ['1m', first_in: '5m15s']
      class: SaveWalletsJob
    sweep_expired_invoices_job:
      every: ['1m', first_in: '5m30s']
      class: SweepExpiredInvoicesJob
