:scheduler:
  :schedule:
    spawn_monero_rpc_wallets_job:
      every: ['1m', first_in: '0s']
      class: SpawnMoneroRpcWalletsJob
    sweep_expired_invoices_job:
      every: ['1m', first_in: '5m']
      class: SweepExpiredInvoicesJob
